#!/usr/bin/env bash


# ************************ Make homebrew install tools at external hard_drive ***************
# On .zprofile
# export HOMEBREW_PREFIX=“/Volumes/hard_drive/homebrew”
# On .zshrc
# export PATH="/Volumes/hard_drive/homebrew/bin:$PATH"
# On .zshrc
# export HOMEBREW_CACHE=/Volumes/hard_drive/homebrew_cache
# On .zshrc
# export PATH="/Volumes/hard_drive/homebrew_cache/bin:$PATH"

# List of tools in alphabetical order
tools=(
    adobe-creative-cloud
    discord
    docker
    docker-completion
    docker-compose
    dropbox
    ffmpeg
    git
    google-chrome
    google-drive
    htop
    iterm2
    microsoft-edge
    notion
    obsidian
    onedrive
    openssh
    openssl
    curl
    speedtest-cli
    tree
    visual-studio-code
    zlib
    zsh-syntax-highlighting
    bat
    go
    mactex
    jq
    xmlstarlet
    parallel
    xsv
    pup
    vowpal-wabbit
    chatgpt
)

for tool in "${tools[@]}"; do
    brew install "$tool"
done

