#!/usr/bin/env bash


# ************************ Make homebrew install tools at external hard_drive ***************
# On .zprofile
export HOMEBREW_PREFIX=/Volumes/YourDriveName/homebrew
# On .zshrc
# export PATH="/Volumes/YourDriveName/homebrew/bin:$PATH"
# On .zshrc
# export HOMEBREW_CACHE=/Volumes/YourDriveName/homebrew_cache
# On .zshrc
# export PATH="/Volumes/YourDriveName/homebrew_cache/bin:$PATH"

# List of tools in alphabetical order
tools=(
    adobe-creative-cloud
    discord
    docker
    docker-completion
    docker-compose
    dbschema
    drawio
    dropbox
    ffmpeg
    fontconfig
    git
    google-chrome
    google-drive
    htop
    imagemagick
    iterm2
    microsoft-edge
    microsoft-office
    microsoft-teams
    nordvpn
    nmap
    notion
    obsidian
    onedrive
    openssh
    openssl
    postman
    speedtest-cli
    tree
    virtualbox
    visual-studio-code
    wireshark
    youtube-dl
    zlib
    zsh-syntax-highlighting
)

for tool in "${tools[@]}"; do
    brew install "$tool"
done
