#!/bin/bash

print_dark_yellow() {
    echo -e "\033[0;33m$1\033[0m"
}

# Packages to install
packages=(
    "git"
    "powerline"
    "software-properties-common"
    "snapd"
    "curl"
    "vim"
    "xclip"
    "bat"
    "htop"
    "build-essential"
    "openssh-server"
    "nmap"
    "openssl"
    "tree"
    "bat"
)

# Install packages using apt-get
sudo apt-get update
for package in "${packages[@]}"; do
    sudo apt-get install -y "$package"
done

# Install bat via snap

# Display reminders
echo "LEMBRE-SE > run: sudo mkdir -p ~/.local/bin"
echo "Lembre-se de rodar: ln -s /usr/bin/batcat ~/.local/bin/bat"
echo "Lembre-se de add >   alias bat='batcat'  "
echo "Depois que instalar o bat"

# End of script
